import specialOne from './image/示例一.png'
import specialTwo from './image/示例二.png'
import specialThere from './image/示例三.png'

const specialData = [
    {
        id: '1',
        name: '示例一.png',
        specificData: [{
            id: 1,
            type: 2,
            img: specialOne,
            name: '示例一.png',
            headData: [{
                id: 1,
                key: '发票代码',
                value: '5000210330',
                startX: 256,
                startY: 292,
                height: 64,
                width: 358,
                rightClick: false,
                deg: 0.0
            }, {
                id: 2,
                key: '发票号码',
                value: '22968322',
                startX: 1428,
                startY: 286,
                height: 117,
                width: 563,
                rightClick: false,
                deg: 0.0
            }, {
                id: 3,
                key: '发票日期',
                value: '2021年06月05日',
                startX: 1695,
                startY: 416,
                height: 45,
                width: 264,
                rightClick: false,
                deg: 0.0
            }, {
                id: 4,
                key: '购买方名称',
                value: '材料有限公司',
                startX: 569,
                startY: 499,
                height: 44,
                width: 203,
                rightClick: false,
                deg: 0.0
            }, {
                id: 5,
                key: '购买方纳税人识别号',
                value: '91347583MA3TJDEF5N',
                startX: 376,
                startY: 548,
                height: 54,
                width: 530,
                rightClick: false,
                deg: 0.0
            }, {
                id: 6,
                key: '购买方地址及电话',
                value: '安徽省池州市010-93470823',
                startX: 372,
                startY: 607,
                height: 35,
                width: 724,
                rightClick: false,
                deg: 0.0
            }, {
                id: 7,
                key: '购买方开户行及账号',
                value: '中国农业银行池州江南支行12984793403940814',
                startX: 373,
                startY: 657,
                height: 41,
                width: 725,
                rightClick: false,
                deg: 0.0
            }, {
                id: 8,
                key: '销售方名称',
                value: '粘胶厂',
                startX: 641,
                startY: 1224,
                height: 39,
                width: 97,
                rightClick: false,
                deg: 0.0
            }, {
                id: 9,
                key: '销售方纳税人识别号',
                value: '917438480038080939',
                startX: 432,
                startY: 1268,
                height: 48,
                width: 487,
                rightClick: false,
                deg: 0.0
            }, {
                id: 10,
                key: '销售方地址及电话',
                value: '广州市白云区020-73905280',
                startX: 385,
                startY: 1318,
                height: 37,
                width: 725,
                rightClick: false,
                deg: 0.0
            }, {
                id: 11,
                key: '销售方开户行及账号',
                value: '广州农村商业银行白云新城支行35879347823820314',
                startX: 385,
                startY: 1364,
                height: 37,
                width: 719,
                rightClick: false,
                deg: 0.0
            }, {
                id: 12,
                key: '不含税总金额',
                value: '75663.72',
                startX: 1384,
                startY: 1089,
                height: 44,
                width: 223,
                rightClick: false,
                deg: 0.0
            }, {
                id: 13,
                key: '总税额',
                value: '9836.28',
                startX: 1794,
                startY: 1093,
                height: 38,
                width: 195,
                rightClick: false,
                deg: 0.0
            }, {
                id: 14,
                key: '价税合计大写',
                value: '捌万伍仟伍佰圆整',
                startX: 594,
                startY: 1150,
                height: 43,
                width: 347,
                rightClick: false,
                deg: 0.0
            }, {
                id: 15,
                key: '价税合计小写',
                value: '85500.00',
                startX: 1600,
                startY: 1155,
                height: 41,
                width: 246,
                rightClick: false,
                deg: 0.0
            }, {
                id: 16,
                key: '密码区',
                value: '4*6<-30*065/+>5-6510*888*94<\n>4<//343>88+-591/951><935-8+\n9++>68/985</>550+-5/17080/8\n8/969244/5+-77<1<6<592>0>57',
                startX: 1237,
                startY: 510,
                height: 162,
                width: 682,
                rightClick: false,
                deg: 0.0
            }, {
                id: 17,
                key: '收款人',
                value: '贺',
                startX: 236,
                startY: 1407,
                height: 37,
                width: 40,
                rightClick: false,
                deg: 0.0
            }, {
                id: 18,
                key: '开票人',
                value: '肖',
                startX: 1203,
                startY: 1418,
                height: 36,
                width: 37,
                rightClick: false,
                deg: 0.0
            }],
            otherData: [{
                id: 19,
                key: '商品名称1',
                value: '*化学合成材料*胶水',
                rightClick: false,
                deg: 0.0
            }, {
                id: 20,
                key: '商品规格型号1',
                value: '802.62D',
                startX: 555,
                startY: 765,
                height: 34,
                width: 126,
                rightClick: false,
                deg: 0.0
            }, {
                id: 21,
                key: '商品单位1',
                value: 'KG',
                startX: 834,
                startY: 763,
                height: 38,
                width: 56,
                rightClick: false,
                deg: 0.0
            }, {
                id: 22,
                key: '商品数量1',
                value: '2000',
                startX: 1036,
                startY: 768,
                height: 33,
                width: 75,
                rightClick: false,
                deg: 0.0
            }, {
                id: 23,
                key: '商品单价1',
                value: '37.831858407',
                startX: 1142,
                startY: 769,
                height: 28,
                width: 172,
                rightClick: false,
                deg: 0.0
            }, {
                id: 24,
                key: '商品金额1',
                value: '75663.72',
                startX: 1470,
                startY: 765,
                height: 38,
                width: 143,
                rightClick: false,
                deg: 0.0
            }, {
                id: 25,
                key: '商品税率1',
                value: '13%',
                startX: 1640,
                startY: 764,
                height: 40,
                width: 69,
                rightClick: false,
                deg: 0.0
            }, {
                id: 26,
                key: '商品税额1',
                value: '9836.28',
                startX: 1874,
                startY: 769,
                height: 34,
                width: 122,
                rightClick: false,
                deg: 0.0
            }]
            ,
            bottomData: [{
                id: 27,
                key: '发票联号',
                value: '第一联:记账联',
                startX: 2014,
                startY: 706,
                height: 243,
                width: 47,
                rightClick: false,
                deg: 0.0
            }],
            originalWidth: 2080,
            originalHeight: 1560
        }],
        url: 'excel/special/示例一.xlsx',
        show: true,
        imgRotatingDeg: 0
    },
    {
        id: '1',
        name: '示例二.png',
        specificData: [{
            id: 1,
            type: 2,
            img: specialTwo,
            name: '示例二.png',
            headData: [{
                id: 1,
                key: '发票代码',
                value: '5000234219',
                startX: 217,
                startY: 180,
                height: 28,
                width: 148,
                rightClick: false,
                deg: 0.0
            }, {
                id: 2,
                key: '发票号码',
                value: '07807207',
                startX: 694,
                startY: 184,
                height: 52,
                width: 234,
                rightClick: false,
                deg: 0.0
            }, {
                id: 3,
                key: '发票日期',
                value: '2021年06月05日',
                startX: 792,
                startY: 240,
                height: 19,
                width: 110,
                rightClick: false,
                deg: 0.0
            }, {
                id: 4,
                key: '购买方名称',
                value: '地产发展有限公司',
                startX: 344,
                startY: 267,
                height: 19,
                width: 111,
                rightClick: false,
                deg: 0.0
            }, {
                id: 5,
                key: '购买方纳税人识别号',
                value: '910934346443343435',
                startX: 266,
                startY: 288,
                height: 20,
                width: 187,
                rightClick: false,
                deg: 0.0
            }, {
                id: 6,
                key: '购买方地址及电话',
                value: '重庆市沙坪坝区023-34815983',
                startX: 265,
                startY: 311,
                height: 18,
                width: 290,
                rightClick: false,
                deg: 0.0
            }, {
                id: 7,
                key: '购买方开户行及账号',
                value: '招商银行重庆江北支行123903149340254',
                startX: 264,
                startY: 334,
                height: 17,
                width: 259,
                rightClick: false,
                deg: 0.0
            }, {
                id: 8,
                key: '销售方名称',
                value: '物资有限公司',
                startX: 329,
                startY: 572,
                height: 18,
                width: 82,
                rightClick: false,
                deg: 0.0
            }, {
                id: 9,
                key: '销售方纳税人识别号',
                value: '917482753470238058',
                startX: 261,
                startY: 592,
                height: 19,
                width: 193,
                rightClick: false,
                deg: 0.0
            }, {
                id: 10,
                key: '销售方地址及电话',
                value: '重庆市沙坪坝区10213593204302',
                startX: 259,
                startY: 611,
                height: 14,
                width: 325,
                rightClick: false,
                deg: 0.0
            }, {
                id: 11,
                key: '销售方开户行及账号',
                value: '建行沙坪坝支行上桥分理处50001053700014150193',
                startX: 260,
                startY: 635,
                height: 18,
                width: 304,
                rightClick: false,
                deg: 0.0
            }, {
                id: 12,
                key: '不含税总金额',
                value: '99710.15',
                startX: 695,
                startY: 515,
                height: 15,
                width: 81,
                rightClick: false,
                deg: 0.0
            }, {
                id: 13,
                key: '总税额',
                value: '12962.32',
                startX: 852,
                startY: 515,
                height: 16,
                width: 80,
                rightClick: false,
                deg: 0.0
            }, {
                id: 14,
                key: '价税合计大写',
                value: '壹拾壹万贰仟陆佰柒拾贰圆肆角柒分',
                startX: 358,
                startY: 542,
                height: 16,
                width: 229,
                rightClick: false,
                deg: 0.0
            }, {
                id: 15,
                key: '价税合计小写',
                value: '112672.47',
                startX: 773,
                startY: 542,
                height: 15,
                width: 98,
                rightClick: false,
                deg: 0.0
            }, {
                id: 16,
                key: '密码区',
                value: '0305/4*/7/>7<94+7>04/5/8+4<\n5<>2104>-66/46*053/8>1*7<70\n5</3840/3294*+038+5479*893/\n8103+18/8*01188/03/9886+<0--',
                startX: 622,
                startY: 272,
                height: 79,
                width: 285,
                rightClick: false,
                deg: 0.0
            }, {
                id: 17,
                key: '收款人',
                value: '李',
                startX: 199,
                startY: 658,
                height: 18,
                width: 22,
                rightClick: false,
                deg: 0.0
            }, {
                id: 18,
                key: '复核',
                value: '陈',
                startX: 414,
                startY: 657,
                height: 19,
                width: 22,
                rightClick: false,
                deg: 0.0
            }, {
                id: 19,
                key: '开票人',
                value: '吴',
                startX: 608,
                startY: 656,
                height: 18,
                width: 19,
                rightClick: false,
                deg: 0.0
            }],
            otherData: [{
                id: 20,
                key: '商品名称1',
                value: '*黑色金属冶炼压延品*螺纹钢\n*黑色金属冶炼压延品*螺纹钢',
                rightClick: false,
                deg: 0.0
            }, {
                id: 21,
                key: '商品规格型号1',
                value: '25\n16',
                startX: 344,
                startY: 372,
                height: 34,
                width: 22,
                rightClick: false,
                deg: 0.0
            }, {
                id: 22,
                key: '商品单位1',
                value: '吨\n吨',
                startX: 447,
                startY: 372,
                height: 34,
                width: 20,
                rightClick: false,
                deg: 0.0
            }, {
                id: 23,
                key: '商品数量1',
                value: '6\n12.911',
                startX: 526,
                startY: 374,
                height: 33,
                width: 46,
                rightClick: false,
                deg: 0.0
            }, {
                id: 24,
                key: '商品单价1',
                value: '4864.77876106\n5462.12389380',
                startX: 579,
                startY: 374,
                height: 32,
                width: 70,
                rightClick: false,
                deg: 0.0
            }, {
                id: 25,
                key: '商品金额1',
                value: '29188.67\n70521.48',
                startX: 717,
                startY: 375,
                height: 32,
                width: 59,
                rightClick: false,
                deg: 0.0
            }, {
                id: 26,
                key: '商品税率1',
                value: '13%\n13%',
                startX: 782,
                startY: 375,
                height: 33,
                width: 29,
                rightClick: false,
                deg: 0.0
            }, {
                id: 27,
                key: '商品税额1',
                value: '3794.53\n9167.79',
                startX: 879,
                startY: 376,
                height: 32,
                width: 52,
                rightClick: false,
                deg: 0.0
            }],
            bottomData: [{
                id: 28,
                key: '发票联号',
                value: '第二联:抵扣联',
                startX: 935,
                startY: 354,
                height: 99,
                width: 19,
                rightClick: false,
                deg: 0.0
            }, {
                id: 29,
                key: '备注',
                value: '项目名称钢材供货合同项目地)电',
                startX: 629,
                startY: 569,
                height: 29,
                width: 246,
                rightClick: false,
                deg: 0.0
            }],
            originalWidth: 1008,
            originalHeight: 756
        }],
        url: 'excel/special/示例二.xlsx',
        show: true,
        imgRotatingDeg: 0
    },
    {
        id: '1',
        name: '示例三.png',
        specificData: [{
            id: 1,
            type: 2,
            img: specialThere,
            name: '示例三.png',
            headData: [{
                id: 1,
                key: '发票号码',
                value: '06468006',
                startX: 889,
                startY: 240,
                height: 67,
                width: 333,
                rightClick: false,
                deg: 0.0
            }, {
                id: 2,
                key: '发票日期',
                value: '2021年03月18日',
                startX: 1050,
                startY: 316,
                height: 27,
                width: 149,
                rightClick: false,
                deg: 0.0
            }, {
                id: 3,
                key: '购买方名称',
                value: '置业有限公司',
                startX: 414,
                startY: 375,
                height: 21,
                width: 109,
                rightClick: false,
                deg: 0.0
            }, {
                id: 4,
                key: '购买方纳税人识别号',
                value: '91453427MA3THEFK43',
                startX: 316,
                startY: 403,
                height: 23,
                width: 295,
                rightClick: false,
                deg: 0.0
            }, {
                id: 5,
                key: '购买方地址及电话',
                value: '福建省泉州市0592-9438450',
                startX: 295,
                startY: 433,
                height: 24,
                width: 431,
                rightClick: false,
                deg: 0.0
            }, {
                id: 6,
                key: '购买方开户行及账号',
                value: '中国建设银行股份有限公司石狮分行43918740809189408033',
                startX: 298,
                startY: 463,
                height: 21,
                width: 423,
                rightClick: false,
                deg: 0.0
            }, {
                id: 7,
                key: '销售方名称',
                value: '建筑材料有限公司',
                startX: 378,
                startY: 795,
                height: 23,
                width: 148,
                rightClick: false,
                deg: 0.0
            }, {
                id: 8,
                key: '销售方纳税人识别号',
                value: '919437580284029303',
                startX: 325,
                startY: 822,
                height: 27,
                width: 290,
                rightClick: false,
                deg: 0.0
            }, {
                id: 9,
                key: '销售方地址及电话',
                value: '厦门市湖里区0592-85360202',
                startX: 302,
                startY: 848,
                height: 32,
                width: 94,
                rightClick: false,
                deg: 0.0
            }, {
                id: 10,
                key: '销售方开户行及账号',
                value: '建行厦门吕岭支行75036028058203843850',
                startX: 304,
                startY: 880,
                height: 20,
                width: 373,
                rightClick: false,
                deg: 0.0
            }, {
                id: 11,
                key: '不含税总金额',
                value: '99963.66',
                startX: 880,
                startY: 709,
                height: 25,
                width: 127,
                rightClick: false,
                deg: 0.0
            }, {
                id: 12,
                key: '总税额',
                value: '12995.28',
                startX: 1103,
                startY: 708,
                height: 24,
                width: 125,
                rightClick: false,
                deg: 0.0
            }, {
                id: 13,
                key: '价税合计大写',
                value: '壹拾壹万贰仟玖佰伍拾捌圆玖角肆分',
                startX: 426,
                startY: 751,
                height: 26,
                width: 361,
                rightClick: false,
                deg: 0.0
            }, {
                id: 14,
                key: '价税合计小写',
                value: '112958.94',
                startX: 1007,
                startY: 747,
                height: 25,
                width: 156,
                rightClick: false,
                deg: 0.0
            }, {
                id: 15,
                key: '密码区',
                value: '<657<9/7-<0*917*7*7+/3-><+7\n>4/<>7>1</6+50713*50/4323+4\n<4383>403*<8<0<83<0<94//<>5\n>>67+6><-<92*/2326546*/6443',
                startX: 788,
                startY: 371,
                height: 97,
                width: 391,
                rightClick: false,
                deg: 0.0
            }, {
                id: 16,
                key: '收款人',
                value: '陈',
                startX: 210,
                startY: 909,
                height: 23,
                width: 25,
                rightClick: false,
                deg: 0.0
            }, {
                id: 17,
                key: '复核',
                value: 'i陈',
                startX: 455,
                startY: 886,
                height: 45,
                width: 78,
                rightClick: false,
                deg: 0.0
            }, {
                id: 18,
                key: '开票人',
                value: '林',
                startX: 774,
                startY: 903,
                height: 23,
                width: 25,
                rightClick: false,
                deg: 0.0
            }],
            otherData: [{
                id: 19,
                key: '商品名称1',
                value: '*金属制品*淋浴花洒',
                rightClick: false,
                deg: 0.0
            }, {
                id: 20,
                key: '商品规格型号1',
                value: 'K-7686T-4-CP',
                startX: 404,
                startY: 526,
                height: 16,
                width: 114,
                rightClick: false,
                deg: 0.0
            }, {
                id: 21,
                key: '商品单位1',
                value: '套',
                startX: 564,
                startY: 522,
                height: 23,
                width: 25,
                rightClick: false,
                deg: 0.0
            }, {
                id: 22,
                key: '商品数量1',
                value: '237',
                startX: 684,
                startY: 523,
                height: 20,
                width: 33,
                rightClick: false,
                deg: 0.0
            }, {
                id: 23,
                key: '商品单价1',
                value: '421.78761062',
                startX: 738,
                startY: 523,
                height: 16,
                width: 98,
                rightClick: false,
                deg: 0.0
            }, {
                id: 24,
                key: '商品金额1',
                value: '99963.66',
                startX: 927,
                startY: 521,
                height: 19,
                width: 75,
                rightClick: false,
                deg: 0.0
            }, {
                id: 25,
                key: '商品税率1',
                value: '13%',
                startX: 1024,
                startY: 520,
                height: 20,
                width: 35,
                rightClick: false,
                deg: 0.0
            }, {
                id: 26,
                key: '商品税额1',
                value: '12995.28',
                startX: 1150,
                startY: 517,
                height: 21,
                width: 75,
                rightClick: false,
                deg: 0.0

            }],
            bottomData: [{
                id: 27,
                key: '发票联号',
                value: '第三联:发票联',
                startX: 1234,
                startY: 481,
                height: 97,
                width: 23,
                rightClick: false,
                deg: 0.0
            }, {
                id: 28,
                key: '备注',
                value: '项目名称:石狮龙湖福江期项目地址:石狮市合同名称：厦门石狮供货合同',
                startX: 791,
                startY: 791,
                height: 87,
                width: 238,
                rightClick: false,
                deg: 0.0
            }],
            originalWidth: 1649,
            originalHeight: 1156
        }],
        url: 'excel/special/示例三.xlsx',
        show: true,
        imgRotatingDeg: 0
    }
]

export {
    specialData
}
