import exampleOne from "../../assets/images/document-images/docOcr/1.png"
import exampleTwo from "../../assets/images/document-images/docOcr/2.jpg"
import exampleThree from "../../assets/images/document-images/docOcr/3.jpg"

const documents = [
  {
    id: "001",
    pages: [
      {
        id: 1,
        wordData: [
          {
            id: 1,
            text: "九、合同文件组成及解释次序：",
            startX: 60,
            startY: 194,
            rightClick: false,
            height: 18,
            width: 148,
            deg: -1,
          },
          {
            id: 2,
            text: "构成本合同的文件应能互相解释，互为说明。除本合同条款另有约定外，本合同文件组成及",
            startX: 78,
            startY: 210,
            rightClick: false,
            height: 18,
            width: 414,
            deg: -1.7,
          },
          {
            id: 3,
            text: "优先解释次序如下：",
            startX: 58,
            startY: 234,
            rightClick: false,
            height: 18,
            width: 90,
            deg: -1.7,
          },
          {
            id: 4,
            text: " 1、本合同签订后双方约定并共同签署的有关工程的约谈记录、变更等书面协议；",
            startX: 78,
            startY: 250,
            rightClick: false,
            height: 18,
            width: 370,
            deg: -1.7,
          },
          {
            id: 5,
            text: " 2、本合同的协议书；",
            startX: 78,
            startY: 274,
            rightClick: false,
            height: 18,
            width: 104,
            deg: -1.7,
          },
          {
            id: 6,
            text: " 3、本合同的专用条款；",
            startX: 78,
            startY: 296,
            rightClick: false,
            height: 18,
            width: 112,
            deg: -1.7,
          },
          {
            id: 7,
            text: "4、本合同的附件；",
            startX: 78,
            startY: 316,
            rightClick: false,
            height: 18,
            width: 90,
            deg: -1.7,
          },
          {
            id: 8,
            text: "5、本合同的通用条款；",
            startX: 78,
            startY: 336,
            rightClick: false,
            height: 18,
            width: 114,
            deg: -1.7,
          },
          {
            id: 9,
            text: "6、现行标准、规范、技术要求和有关技术资料；",
            startX: 78,
            startY: 356,
            rightClick: false,
            height: 18,
            width: 228,
            deg: -1.7,
          },
          {
            id: 10,
            text: " 7、工程图纸",
            startX: 78,
            startY: 378,
            rightClick: false,
            height: 18,
            width: 68,
            deg: -1.7,
          },
          {
            id: 11,
            text: "8、材料样板；",
            startX: 78,
            startY: 398,
            rightClick: false,
            height: 18,
            width: 74,
            deg: -1.7,
          },
          {
            id: 12,
            text: "9、本合同的合同计价清单；",
            startX: 78,
            startY: 418,
            rightClick: false,
            height: 18,
            width: 130,
            deg: -1.7,
          },
        ],
        img: exampleOne,
        originalWidth: "501",
        originalHeight: "437",
        imgRotatingDeg: 0,
        scale: "",
      },
    ],
    name: "示例一.jpg",
  },
  {
    id: "002",
    pages: [
      {
        id: 1,
        wordData: [
          {
            id: 1,
            text: "产品手册内容化框架",
            startX: 424,
            startY: 472,
            rightClick: false,
            height: 44,
            width: 320,
            deg: 1.1,
          },
          {
            id: 2,
            text: "1.产品名称",
            startX: 124,
            startY: 592,
            rightClick: false,
            height: 48,
            width: 204,
            deg: 0,
          },
          {
            id: 3,
            text: "企业级OCR解决方案",
            startX: 192,
            startY: 652,
            rightClick: false,
            height: 48,
            width: 360,
            deg: 0,
          },
          {
            id: 4,
            text: "2.产品介绍",
            startX: 112,
            startY: 712,
            rightClick: false,
            height: 56,
            width: 220,
            deg: 0,
          },
          {
            id: 5,
            text: "在企业运行的多个环节上有大量的证件、票据、合同等各",
            startX: 180,
            startY: 780,
            rightClick: false,
            height: 44,
            width: 884,
            deg: 0,
          },
          {
            id: 6,
            text: "种类型的纸质文档。这些文档受限于纸质文档的存储形式,无法被编",
            startX: 112,
            startY: 848,
            rightClick: false,
            height: 40,
            width: 956,
            deg: 0,
          },
          {
            id: 7,
            text: "辑和检索,往往丧失它的数据价值,借助联易融的OCR解决方案可",
            startX: 108,
            startY: 916,
            rightClick: false,
            height: 40,
            width: 964,
            deg: 0,
          },
          {
            id: 8,
            text: "以很好的将纸质材料中的信息进行结构化信息提取,帮助企业整理、",
            startX: 108,
            startY: 984,
            rightClick: false,
            height: 40,
            width: 956,
            deg: 0,
          },
          {
            id: 9,
            text: "整合纸质材料数据价值,加快企业数字化建设。",
            startX: 104,
            startY: 1052,
            rightClick: false,
            height: 44,
            width: 680,
            deg: 0,
          },
          {
            id: 10,
            text: " 3.核心优势",
            startX: 100,
            startY: 1120,
            rightClick: false,
            height: 52,
            width: 220,
            deg: 0,
          },
          {
            id: 21,
            text: "1.定制化解决方案:",
            startX: 100,
            startY: 1196,
            rightClick: false,
            height: 44,
            width: 288,
            deg: 0,
          },
          {
            id: 11,
            text: "为企业提供定制化的OCR解决方案,使得人工智能技术更加适配",
            startX: 151,
            startY: 1274,
            rightClick: false,
            height: 45,
            width: 948,
            deg: 0,
          },
          {
            id: 12,
            text: "企业应用场景。",
            startX: 92,
            startY: 1340,
            rightClick: false,
            height: 48,
            width: 232,
            deg: 0,
          },
          {
            id: 13,
            text: "2.种类丰富:",
            startX: 88,
            startY: 1416,
            rightClick: false,
            height: 48,
            width: 196,
            deg: 0,
          },
          {
            id: 14,
            text: "联易融OCR解决方案将提供20+OCR服务场景解析方案,涵盖",
            startX: 147,
            startY: 1498,
            rightClick: false,
            height: 36,
            width: 968,
            deg: 0,
          },
          {
            id: 15,
            text: "供应链金融、跨境、企业认证等多个领域。",
            startX: 87,
            startY: 1574,
            rightClick: false,
            height: 45,
            width: 652,
            deg: 0,
          },
          {
            id: 16,
            text: "3.快速响应:",
            startX: 84,
            startY: 1652,
            rightClick: false,
            height: 48,
            width: 196,
            deg: 0,
          },
          {
            id: 17,
            text: "联易融各类场景下的OCR技术响应速度均在1s以内。",
            startX: 135,
            startY: 1736,
            rightClick: false,
            height: 44,
            width: 844,
            deg: 0,
          },
          {
            id: 18,
            text: "4.功能特点",
            startX: 79,
            startY: 1808,
            rightClick: false,
            height: 60,
            width: 240,
            deg: 0,
          },
          {
            id: 19,
            text: "企业资质认证:针对企业资质认证场景,提供身份证、营业执照,",
            startX: 135,
            startY: 1898,
            rightClick: false,
            height: 47,
            width: 1000,
            deg: 0,
          },
          {
            id: 20,
            text: "企业财报等材料的解析服务。",
            startX: 75,
            startY: 1985,
            rightClick: false,
            height: 46,
            width: 456,
            deg: 0,
          },
        ],
        img: exampleTwo,
        originalWidth: "1165",
        originalHeight: "2560",
        imgRotatingDeg: 0,
        scale: "",
      },
    ],
    name: "示例二.jpg",
  },
  {
    id: "003",
    pages: [
      {
        id: 1,
        wordData: [
          {
            id: 1,
            text: "联易融在腾讯等早期股东的支持下，于 2016 年 2 月成立于深圳，通过五年多的发展，成为国内领先的供",
            startX: 372,
            startY: 311,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 2,
            text: "应链金融科技服务提供商。目前联易融依托在东南亚地区的业务布局，向全球扩张。“新加坡是亚太地区",
            startX: 375,
            startY: 379,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 3,
            text: "最重要的金融中心之一。它为贸易金融提供了良好的发展条件，并营造了一个直观、数字友好的环境。”",
            startX: 372,
            startY: 442,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 4,
            text: " 宋群强调。",
            startX: 372,
            startY: 505,
            rightClick: false,
            height: 50,
            width: 170,
            deg: 0,
          },
          {
            id: 5,
            text: " 联易融致力于通过科技和创新来重新定义和改造供应链金融，其云原生解决方案可以优化供应链金融的支",
            startX: 375,
            startY: 638,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 6,
            text: "付周期，实现供应链金融全流程的数字化。宋群表示，“通过定制化的解决方案和行业领先的科技，联易融",
            startX: 375,
            startY: 705,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 7,
            text: "向核心企业和金融机构提供世界领先的供应链金融科技解决方案，同时为中小企业提供卓越的用户体验。",
            startX: 375,
            startY: 768,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 8,
            text: "我们的员工中有 60%以上是开发人员，规模强大的技术团队，为我们开发新产品提供了强有力的支撑。” ",
            startX: 375,
            startY: 835,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 9,
            text: "国际金融公司（International Finance Corporation, IFC）估测，目前中小企业的融资缺口达 5.2 万亿美",
            startX: 378,
            startY: 968,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 10,
            text: "元，其中大部分需求都在亚洲。联易融希望利用创新技术解决这部分的资金缺口，提升科技在供应链领域",
            startX: 372,
            startY: 1028,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 11,
            text: "的应用。“联易融期待与更多新加坡公司合作，运用新兴科技工具，优化供应链金融流程，助力企业实现",
            startX: 372,
            startY: 1091,
            rightClick: false,
            height: 50,
            width: 1746,
            deg: 0,
          },
          {
            id: 12,
            text: "更加快捷高效的跨境贸易融资交易，”宋群表示。",
            startX: 375,
            startY: 1158,
            rightClick: false,
            height: 50,
            width: 806,
            deg: 0,
          },
        ],
        img: exampleThree,
        originalWidth: "2481",
        originalHeight: "3508",
        imgRotatingDeg: 0,
        scale: "",
      },
    ],
    name: "示例三.jpg",
  },
]
export default documents