import normalOne from "./image/示例二.png";
import normalTwo from "./image/示例一.png";

const normalData = [
  {
    id: "1",
    name: "示例一.png",
    path: "/product/business_license_analysis/lls/T2022042011708808/",
    url: "excel/示例一.xlsx",
    requestId: "001",
    show: true,
    images: [
      {
        imgRotatingDeg: 0,
        index: 1,
        name: "示例一.png",
        originalHeight: 4961,
        originalWidth: 3508,
        path: "/product/business_license_analysis/lls/T2022042011708808/data/示例一.png",
        url: normalOne,
      },
    ],
    items: [
      {
        angle: 0,
        imageHeight: 4961,
        imageWidth: 3508,
        index: 1,
        items: [
          {
            height: 65,
            id: 1,
            key: "统一社会信用代码",
            startX: 2189,
            startY: 1840,
            value: "88888888888888888E",
            width: 635,
          },

          {
            height: 64,
            id: 2,
            key: "编号",
            startX: 2265,
            startY: 1652,
            value: "S1234567812345(5-2)",
            width: 669,
          },
          {
            height: 98,
            id: 3,
            key: "公司名称",
            startX: 1099,
            startY: 2000,
            value: "安装有限公司",
            width: 476,
          },
          {
            height: 89,
            id: 4,
            key: "公司类型",
            startX: 1094,
            startY: 2138,
            value: "有限责任公司",
            width: 481,
          },
          {
            height: 94,
            id: 5,
            key: "法定代表人",
            startX: 1094,
            startY: 2401,
            value: "代用名",
            width: 253,
          },
          {
            height: 357,
            id: 6,
            key: "经营范围",
            startX: 1079,
            startY: 2936,
            value:
              "建筑安装业(具体经营项目请登录广州市商事主体信息公示平台建筑安装业(具体经营项目请登录广州市商事主体查询。依法须经批准的项目,经相关部门批准后方可开展经营活动。)",
            width: 1667,
          },
          {
            height: 84,
            id: 7,
            key: "注册资本（中文）",
            startX: 1099,
            startY: 2540,
            value: "人民币壹仟万元",
            width: 561,
          },
          {
            height: 84,
            id: 8,
            key: "注册资本（数字）",
            startX: 1099,
            startY: 2540,
            value: "10000000 人民币",
            width: 561,
          },

          {
            height: 80,
            id: 9,
            key: "成立日期",
            startX: 1093,
            startY: 2672,
            value: "2019年4月1日",
            width: 596,
          },
          {
            height: 85,
            id: 10,
            key: "营业期限",
            startX: 1089,
            startY: 2802,
            value: "2019年4月1日至2069年3月31日",
            width: 1354,
          },
          {
            height: 89,
            id: 11,
            key: "地址",
            startX: 1089,
            startY: 2272,
            value: "深圳市南山区科苑南路3099号",
            width: 1077,
          },
        ],
        name: "示例一.png",
        path: "/product/business_license_analysis/lls/T2022042011708808/",
        url: "/product/business_license_analysis/lls/T2022042011708808/示例一.xlsx",
      },
    ],
  },
  {
    id: "1",
    name: "示例二.png",
    path: "/product/business_license_analysis/lls/T2022042013881322/",
    url: "excel/示例二.xlsx",
    requestId: "002",
    show: true,
    images: [
      {
        imgRotatingDeg: 0,
        index: 1,
        name: "示例二.png",
        originalHeight: 1243,
        originalWidth: 700,
        path: "/product/business_license_analysis/lls/T2022042013881322/data/示例二.png",
        url: normalTwo,
      },
    ],
    items: [
      {
        angle: 0,
        imageHeight: 1243,
        imageWidth: 700,
        index: 1,
        items: [
          {
            height: 11,
            id: 1,
            key: "统一社会信用代码",
            startX: 450,
            startY: 505,
            value: "9141072173246453X5",
            width: 130,
          },

          {
            id: 2,
            key: "编号",
          },
          {
            height: 14,
            id: 3,
            key: "公司名称",
            startX: 219,
            startY: 557,
            value: "机械有限责任公司",
            width: 125,
          },
          {
            height: 13,
            id: 4,
            key: "公司类型",
            startX: 220,
            startY: 581,
            value: "有限责任公司(自然人投资或控股)",
            width: 232,
          },
          {
            height: 18,
            id: 5,
            key: "法定代表人",
            startX: 220,
            startY: 633,
            value: "江发呆",
            width: 49,
          },
          {
            height: 133,
            id: 6,
            key: "经营范围",
            startX: 223,
            startY: 746,
            value:
              "振动机械、提升设备、输送设备、混合设备、粉体设备、纺织机械、金属丝网、过滤器、紧固件制造;五金交电批发、零售及从事货物和技术的进出口贸易(国家法律法规规定应经审批方可经营或禁止进出口的货物和技术除外)**(依法须经批准的项目,经相关部门批准后方可开展经营活动)",
            width: 363,
          },
          {
            height: 16,
            id: 7,
            key: "注册资本（中文）",
            startX: 221,
            startY: 659,
            value: "伍佰伍拾万圆整",
            width: 111,
          },
          {
            height: 16,
            id: 8,
            key: "注册资本（数字）",
            startX: 221,
            startY: 659,
            value: "5500000",
            width: 111,
          },
          {
            height: 16,
            id: 9,
            key: "成立日期",
            startX: 220,
            startY: 687,
            value: "2001年10月16日",
            width: 111,
          },
          {
            height: 11,
            id: 10,
            key: "营业期限",
            startX: 221,
            startY: 715,
            value: "2007年04月28日至2036年04月27日",
            width: 236,
          },
          {
            id: 11,
            key: "地址",
            value: "新乡县",
          },
        ],
        name: "示例二.png",
        path: "/product/business_license_analysis/lls/T2022042013881322/",
        url: "/product/business_license_analysis/lls/T2022042013881322/示例二.xlsx",
      },
    ],
  },
];
export { normalData };

// const data = [
//   {
//     id: "1",
//     name: "示例一.png",
//     path: "/product/business_license_analysis/示例一-2022041740974248/",
//     url: "/product/business_license_analysis/示例一-2022041740974248/示例一.xlsx",
//     images: [
//       {
//         imgRotatingDeg: 0,
//         index: 1,
//         name: "示例一.png",
//         originalHeight: 810,
//         originalWidth: 1080,
//         path: "/product/business_license_analysis/示例一-2022041740974248/示例一.png",
//         url: oneUrl,
//       },
//     ],
//     items: [
//       {
//         angle: 0,
//         imageHeight: 810,
//         imageWidth: 1080,
//         index: 1,
//         items: [
//           {
//             height: -16,
//             key: "统一社会信用代码",
//             startX: 66,
//             startY: 288,
//             value: "91341024MA2UXG2X4C",
//             width: 128,
//           },

//           {
//             height: -23,
//             key: "公司名称",
//             startX: 186,
//             startY: 403,
//             value: "祁门县古乐建设工程有限责任公司",
//             width: 259,
//           },
//           {
//             height: -18,
//             key: "公司类型",
//             startX: 186,
//             startY: 438,
//             value: "有限责任公司(非自然人投资或控股的法人独资)",
//             width: 294,
//           },
//           {
//             height: -20,
//             key: "法定代表人",
//             startX: 185,
//             startY: 481,
//             value: "汪荣木",
//             width: 56,
//           },
//           {
//             height: -47,
//             key: "经营范围",
//             startX: 183,
//             startY: 547,
//             value:
//               "民房建筑修缮:河道清理、护岸施工;环境污染治理工程施工:林木采伐、运输。(依法须经批准的项目,经相关部门批准后方可开展经营活动)",
//             width: 366,
//           },
//           {
//             height: -20,
//             key: "注册资本（中文）",
//             startX: 712,
//             startY: 398,
//             value: "壹拾伍万圆整",
//             width: 109,
//           },

//           {
//             height: -22,
//             key: "成立日期",
//             startX: 711,
//             startY: 438,
//             value: "2020年06月19日",
//             width: 127,
//           },
//           {
//             height: -20,
//             key: "营业期限",
//             startX: 715,
//             startY: 478,
//             value: "/长期",
//             width: 53,
//           },
//           {
//             height: -42,
//             key: "地址",
//             startX: 712,
//             startY: 539,
//             value: "安徽省黄山市祁门县古溪乡古溪村委会内",
//             width: 301,
//           },
//         ],
//         name: "/product/business_license_analysis/示例一-2022041740974248/示例一.png",
//         url: "https://beefeather-ng-front.lianyirong.com.cn/file-handle-web/file/img?filename=/product/business_license_analysis/示例一-2022041740974248/示例一.png",
//       },
//     ],
//   },
// ];
// export { data };
